language: node_js
node_js: 8

services:
  - docker

install:
  - Xvfb :1 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :1 -ac >& /dev/null &
  - Xvfb :2 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :2 -ac >& /dev/null &
  - Xvfb :3 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :3 -ac >& /dev/null &
  - ./tools/travis/openwhisk/openwhisk.sh &
  - ow=$!
  - npm ci
  - if [ "$MOCHA_RUN_TARGET"] == "webpack" ]; then (npm run proxy &); (npm run webpack &); fi
  - wait $ow

jobs:
  include:
    - stage: test
      script: npm run test
      env: LAYERS="openwhisk1 openwhisk-editor grid" MOCHA_RUN_TARGET=electron
    - stage: test
      script: npm run test
      # re: second auth see plugins/plugin-openwhisk/src/test/openwhisk2/auth.ts
      env: LAYERS=openwhisk2 MOCHA_RUN_TARGET=electron NEEDS_SECOND_OPENWHISK_AUTH=true NEEDS_OPENWHISK_API_GATEWAY=true NEEDS_OPENWHISK_JAVA8=true
    - stage: test
      script: npm run test
      env: LAYERS=openwhisk3 MOCHA_RUN_TARGET=electron
    - stage: test
      script: npm run test
      env: LAYERS="openwhisk4 composer1" MOCHA_RUN_TARGET=electron NEEDS_OPENWHISK_NODEJS8=true
    - stage: test
      script: npm run test
      env: LAYERS=composer2 MOCHA_RUN_TARGET=electron

env:
  global:
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - PATH=bin:$PATH
    - KEY=${TRAVIS_JOB_NUMBER}
    - PORT_OFFSET=1
    - LOCAL_OPENWHISK=true # allows e.g. openwhisk/src/test/openwhisk1/headless to avoid trying to host set <not-local>
    - NO_OPENWHISK_API_MGMT=true # no openwhisk api management support
    - IGNORE_CERTS=true # apache-composer needs this, because it doesn't obey INSECURE_SSL in wskprops
    - TEST_ORG=testorg
    - TEST_SPACE=testspace
    - NEEDS_OPENWHISK=true
