language: node_js
node_js: 12

services:
  - docker

install:
  - Xvfb :1 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :1 -ac >& /dev/null &
  - Xvfb :2 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :2 -ac >& /dev/null &
  - Xvfb :3 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :3 -ac >& /dev/null &
  - ./tools/travis/openwhisk/openwhisk.sh &
  - ow=$!
  - npm ci
  - wait $ow

# below, the various stages will define S and T
script: npm run test:$T $LAYERS

# re: second auth see plugins/plugin-openwhisk/src/test/openwhisk2/auth.ts
jobs:
  include:
    - env: LAYERS=composer1
    - env: LAYERS=composer2
    - env: LAYERS=openwhisk1
    - env: LAYERS=grid
    - env: LAYERS=openwhisk2 NEEDS_SECOND_OPENWHISK_AUTH=true NEEDS_OPENWHISK_API_GATEWAY=true NEEDS_OPENWHISK_JAVA8=true
    - env: LAYERS=openwhisk3
    - env: LAYERS=openwhisk4 NEEDS_OPENWHISK_NODEJS8=true

env:
  global:
    - T=electron # default target (the other being T=webpack)
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - PATH=bin:$PATH
    - KEY=${TRAVIS_JOB_NUMBER}
    - PORT_OFFSET=1
    - LOCAL_OPENWHISK=true # allows e.g. openwhisk/src/test/openwhisk1/headless to avoid trying to host set <not-local>
    - NO_OPENWHISK_API_MGMT=true # no openwhisk api management support
    - IGNORE_CERTS=true # apache-composer needs this, because it doesn't obey INSECURE_SSL in wskprops
    - TEST_ORG=testorg
    - TEST_SPACE=testspace
    - NEEDS_OPENWHISK=true
    - KUI_TEST_PARALLEL=true
